kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: whoami
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: jwilder/whoami
        ports:
          - name: whoami-iternal
            containerPort: 8000

